# Generated by Django 5.2 on 2025-04-16 23:29

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('key', models.CharField(editable=False, max_length=64, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^[a-z0-9._-]+$', 'Question key must only contain lowercase alphanumeric characters and hyphens.')])),
                ('type', models.CharField()),
                ('choice_text', models.CharField(max_length=512)),
                ('with_comment', models.BooleanField(default=False)),
                ('comment_text', models.CharField(blank=True, max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('value', models.IntegerField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, max_length=512, null=True)),
                ('reference', models.CharField(blank=True, max_length=64, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedback.question')),
            ],
        ),
    ]
