services:
  api:
    environment:
      DB_URL: postgresql://user:pass@db:5432/feedback
    build: ./back-end/
    command: -w 4 -b 0.0.0.0:8000
    ports:
      - 5000:8000
  ui:
    build: ./front-end/
    ports:
      - 8081:80
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: feedback
  test:
    build: ./test/
    command:
      - -v
      - URL:http://localhost:8081
      - -d
      - /out
    network_mode: host
    volumes:
      - ${PWD}/out:/out
