services:
  api:
    environment:
      FEEDBACK_DB_URL: postgresql://user:pass@db:5432/feedback
      FEEDBACK_URL: http://localhost:5000
    build: ./back-end/
    command: -w 4 -b 0.0.0.0:8000
    ports:
      - 5000:8000
  ui:
    build: .
    ports:
      - 8081:80
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: feedback
  test:
    build: ./test/
    environment:
      BASE_URL: http://localhost:8081
    command:
      - -d
      - /out
    network_mode: host
    volumes:
      - ${PWD}/out:/out
