include:
  - docker-compose.yml
services:
  test:
    build: ./test/
    network_mode: host
    environment:
      BASE_URL: http://localhost:8080
    command:
      - -d
      - /out
    volumes:
      - ${PWD}/out:/out
