name: Format
on:
  pull_request:
    branches:
      - main

jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          node-version: "18"
      - name: Check formatting
        run: |
          npm i -g prettier
          prettier . --check
  pycodestyle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v2
        with:
          python-version: "3.11"
      - name: Check formatting
        run: |
          pip install pycodestyle
          pycodestyle --exclude back-end/server/settings.py,*/migrations/*.py .
