name: Images
on:
  push:
    branches:
      - main
    paths:
      - back-end/**
      - front-end/**
      - test/**
      - docker-compose*
  pull_request:
    branches:
      - main
    paths:
      - back-end/**
      - front-end/**
      - test/**
      - docker-compose*

jobs:
  test:
    name: Test container images
    runs-on: ubuntu-latest
    strategy:
      matrix:
        test:
          - host-net
          - proxy-pass
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Test container images
        run: |
          docker compose -f docker-compose.test-${{ matrix.test }}.yml up --exit-code-from test
      - name: Store logs
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: acceptance-test-${{ matrix.test }}-logs
          path: out/
  push:
    name: Push container images
    if: github.ref == 'refs/heads/main'
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push container image to GitHub Container Registry
        run: |
          docker build back-end/ -t back-end
          docker build front-end/ -t front-end
          for tag in ${{ github.run_number }} latest; do
            docker tag back-end ghcr.io/kangasta/three-tier-example-app-api:$tag
            docker push ghcr.io/kangasta/three-tier-example-app-api:$tag
            docker tag front-end ghcr.io/kangasta/three-tier-example-app-ui:$tag
            docker push ghcr.io/kangasta/three-tier-example-app-ui:$tag
          done
